### ISSUE TITLE
AspNetCoreDemos.DemoShell name space is not found for ASP demos

### ISSUE THREAD

**Issue by wangruicheng921** [DevExpress/devextreme-demos#1200]
I clone this repository to my local , and find "AspNetCoreDemos.DemoShell"  NameSpace  is not found 。 I can't solve this problem，If you could help me, I'd be most grateful。

using AspNetCoreDemos.DemoShell;
public class StartUp{
     ···ohter code···
}

**Comment by AlisherAmonulloev** [comment]
Thank you for your patience. Demos in the MVCDemos and NetCoreDemos directories are published for development only and require projects from our internal repositories which are not publicly available. If you need to run our ASP.NET MVC and ASP.NET Core demos, use our installation file. Please use one of the following links to download it:

1. For trial users: https://www.devexpress.com/products/try/
2. For licensed users: https://www.devexpress.com/ClientCenter/DownloadManager/

We will update our Readme to reflect this.
